config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Read all
  get "/tasks", to: "tasks#index"
  # Create
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  # Read one
  get "/tasks/:id", to: "tasks#find", as: :task_id
  # Update
  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "/tasks/:id", to: "tasks#update"
  # Delete
  delete "/tasks/:id", to: "tasks#destroy"

  ### resources :tasks ###
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks_list = Task.all
    @status = ''
  end

  # show method
  def find
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_id_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_id_path(task)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  # def set_task
  #   @task = Task.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%# <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head> %>

<h1>Edit task: <%= @task.title %></h1>
<% @task.completed = true %>

<%= form_with model: @task, url: task_id_path(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit "Update Task" %>
  <br><br>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
<% end %>
<br>

<%# <div class="task-check">
  <input type="checkbox" id="completed">
  <label for="completed">Completed</label><br> %>
  <%# @task.completed = true %>
  <%#= @task.completed %>
<%# </div>
<br> %>

<hr>
<i class="fa-solid fa-rotate-left"></i><%= link_to " Back to list", tasks_path %>

<script src="../../javascript/application.js"></script>

app/views/tasks/find.html.erb
<div>
  <%= link_to "Edit", task_edit_path(@task) %>
  <h1><%= @task.title %></h1>
</div>

<p class="description"><%= @task.details %></p>

<%
  status_id = ''
  message = ''
  if @task.completed == true
    status_id = 'checked'
    message = 'This task is completed.'
  else
    status_id = 'unchecked'
    message = 'This task is not completed yet.'
  end
%>
<p><input type="checkbox" <%= status_id %>> <%= message%></p>
<br>

<hr>
<i class="fa-solid fa-rotate-left"></i><%= link_to " Back to list", tasks_path, class: "no_underline" %>

<%# <%= link_to "Remove",
  task_id_path(@task),
  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
%>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<%#= @tasks_list %>

<% @tasks_list.each do |task| %>
  <% if task.completed == true
      @status = 'checked'
     else
      @status = 'unchecked'
     end
  %>
  <input type="checkbox" <%= @status %>> <%= link_to task.title, task_id_path(task.id), class: "no_underline" %>&nbsp;
  <%= link_to '',
    task_id_path(task),
    class: "fa-regular fa-trash-can",
    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
  %>
  <br>
<% end %>
<br>
<hr>
<%= link_to "+ Add a new task", tasks_new_path, class: "no_underline" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit "Create Task" %>
<% end %>
<br>

<hr>
<i class="fa-solid fa-rotate-left"></i><%= link_to " Back to list", tasks_path, class:"no_underline" %>